[package]
name = "surreal-ts"
version = "1.4.2"
edition = "2021"
license = "GPL-3.0-only"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.1", features = ["derive"] }
convert_case = "0.6.0"
nom = "7.1.3"
regex = "1.10.3"
serde = "1.0.196"
surrealdb = "1.2.0"
tokio = "1.36.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
