[package]
name = "surreal-ts"
version = "1.4.0"
edition = "2021"
license = "GPL-3.0-only"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
convert_case = "0.6.0"
nom = "7.1.3"
regex = "1.10.2"
serde = "1.0.193"
surrealdb = "1.0.1"
tokio = "1.35.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
