[package]
name = "surreal-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
itertools = "0.11.0"
nom = "7.1.3"
serde = "1.0.188"
surrealdb = "1.0.0"
tokio = "1.32.0"

[profile.release]
strip = true
lto = true
codegen-units = 1