[package]
name = "surreal-ts"
version = "1.5.3"
edition = "2021"
license = "GPL-3.0-only"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
convert_case = "0.6.0"
nom = "7.1.3"
serde = "1.0.204"
surrealdb = { version = "1.5.4", features = ["protocol-http"] }
tokio = "1.39.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
