[package]
name = "surreal-ts"
version = "1.2.0"
edition = "2021"
license = "GPL-3.0-only"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
convert_case = "0.6.0"
nom = "7.1.3"
regex = "1.9.6"
serde = "1.0.188"
surrealdb = "1.0.0"
tokio = "1.32.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
